version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    versioning-strategy: increase
    groups:
      go-dependencies:
        patterns: ["*"]

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly" 
    open-pull-requests-limit: 2
    versioning-strategy: increase
    groups:
      docker-updates:
        patterns: ["*"]
